export const INITIALIZE_CITIES = 'INITIALIZE_CITIES';
export const SHORTLIST_CITIES = 'SHORTLIST_CITIES';
export const DELETE_CITIES = 'DELETE_CITIES';
export const SEARCH_CITIES = 'SEARCH_CITIES';
export const SEARCH_CITIES_LIST = 'SEARCH_CITIES_LIST';
export const ADD_NEW_CITIES = 'ADD_NEW_CITIES';
export const SHOW_MODAL = 'SHOW_MODAL';

